### ISSUE TITLE
Can't work if time is less than one minute.

### ISSUE THREAD

**Issue by Shagunjain10** [Ankit404butfound/awesomepy#2]
In **sendwhatmsg** function if time is less than one minute.

File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywhatkit\__init__.py", line 93, in sendwhatmsg
    raise CallTimeException("Call time must be greater than one minutea as web.whatsapp.com takes some time to load")
pywhatkit.CallTimeException: Call time must be greater than one minutea as web.whatsapp.com takes some time to load

**Comment by Ankit404butfound** [comment]
> In **sendwhatmsg** function if time is less than one minute.
> 
> File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pywhatkit__init__.py", line 93, in sendwhatmsg
> raise CallTimeException("Call time must be greater than one minutea as web.whatsapp.com takes some time to load")
> pywhatkit.CallTimeException: Call time must be greater than one minutea as web.whatsapp.com takes some time to load

That is intentional. Web takes some time to load.
