### ISSUE TITLE
How to open it in a browser other than 'default browser' on windows.

### ISSUE THREAD

**Issue by utkarsh48** [Ankit404butfound/awesomepy#3]

**Comment by Ankit404butfound** [comment]
Try this
browser = web.get("C:/user...path...to...browser")
browser.open('https://web.whatsapp.com/send?phone='+phone_no+'&text='+
message)
You need to do proper changes in the source code.

**Comment by utkarsh48** [comment]
Still **it doesn't send the Message**(irrespective of browser), Instead it just pre-writes the message to be sent.(waiting for user to click on send button > )

**Comment by Ankit404butfound** [comment]
Make sure not to interrupt the process from the moment it opens web till
the time it is supposed to send the message.
Message me on Telegram if the error persists. My user name is Tag_kiya_kya.
