### ISSUE TITLE
Youtube Search Not Working (List Index out of Range)

### ISSUE THREAD

**Issue by DeepakChakravarthy** [Ankit404butfound/awesomepy#4]
@Ankit404butfound  
 
 **FYKI**

![image](https://user-images.githubusercontent.com/42644785/86622780-1be72700-bfde-11ea-9d2b-eee311151a6e.png)

Pywhatkit **List Index out of range**

**Comment by Ankit404butfound** [comment]
Hello Deepak

Yes, I am well aware of the fact that the function us not working. It is
due to recent changes in the architecture of YouTube.

You can expect some updates in a day or two.

Regards.

**Comment by Ankit404butfound** [comment]
> @Ankit404butfound
> 
> **FYKI**
> 
> ![image](https://user-images.githubusercontent.com/42644785/86622780-1be72700-bfde-11ea-9d2b-eee311151a6e.png)
> 
> Pywhatkit **List Index out of range**

The update has been released.

**Comment by DeepakChakravarthy** [comment]
@Ankit404butfound 

Thank You for your **Fast Response to Solve this Issue**😊

**I am avid to see more features** on pywhatkit
